组服务器的

2016-08-09 16:08:24,096 INFO  [main-logic-thread-1] rydl.group.msg.handlers.MapGroupHandler:handle MapGroupHandler.java:60 - 玩家[史密斯·米莉(vstargame_s1_5146474)]进行地图[1001,1]传送
2016-08-09 16:08:24,096 INFO  [main-logic-thread-1] rydl.group.msg.handlers.MapGroupHandler:handle MapGroupHandler.java:100 - 玩家[史密斯·米莉(vstargame_s1_5146474)]离开了旧地图[131073,1], 进入了新地图[1001,1]
2016-08-09 16:08:24,096 INFO  [main-logic-thread-1] rydl.group.msg.handlers.LoginGroupHandler:handle LoginGroupHandler.java:493 - 开始接收玩家数据
2016-08-09 16:08:24,096 INFO  [main-logic-thread-1] rydl.group.msg.handlers.LoginGroupHandler:handle LoginGroupHandler.java:506 - 收到玩家[米勒·安倪]的基础数据
2016-08-09 16:08:24,096 INFO  [main-logic-thread-1] rydl.group.msg.handlers.LoginGroupHandler:handle LoginGroupHandler.java:635 - 接收玩家数据结束，已提交到存储队列4506914826420224
2016-08-09 16:08:24,096 INFO  [main-logic-thread-1] rydl.group.msg.handlers.LoginGroupHandler:handle LoginGroupHandler.java:493 - 开始接收玩家数据
2016-08-09 16:08:24,096 INFO  [main-logic-thread-1] rydl.group.msg.handlers.LoginGroupHandler:handle LoginGroupHandler.java:506 - 收到玩家[烏龜蛋]的基础数据
2016-08-09 16:08:24,096 INFO  [main-logic-thread-1] rydl.group.msg.handlers.LoginGroupHandler:handle LoginGroupHandler.java:635 - 接收玩家数据结束，已提交到存储队列4506904363466752
2016-08-09 16:08:24,117 ERROR [GroupServerScheduler_Worker-4] rydl.group.database.cache.CharacterCacheDataManager:saveDbImpl CharacterCacheDataManager.java:299 - 
java.sql.BatchUpdateException: Duplicate entry '0' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor99.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1160)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1773)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1257)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:959)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:1723)
	at rydl.group.database.dao.ItemModelDAO$5.handleWrite(ItemModelDAO.java:356)
	at rydl.commons.kxdb.KxDB.saveOrUpdate(KxDB.java:135)
	at rydl.group.database.dao.ItemModelDAO.batchInsert(ItemModelDAO.java:335)
	at rydl.group.database.services.ItemDbService.saveItems(ItemDbService.java:40)
	at rydl.group.database.cache.CharacterCacheDataManager.saveCharacterDataDbImpl(CharacterCacheDataManager.java:327)
	at rydl.group.database.cache.CharacterCacheDataManager.saveDbImpl(CharacterCacheDataManager.java:296)
	at rydl.group.database.job.CharacterSaveDbJob.execute(CharacterSaveDbJob.java:21)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '0' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor26.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1751)
	
	
	

	... 12 more

	
13
2016-08-08 05:13:04,016 INFO  [GroupServerScheduler_Worker-4] rydl.group.database.cache.CharacterCacheDataManager:saveCharacterDataDbImpl CharacterCacheDataManager.java:342 - 存储玩家[藍夢瑤(4506901631205376)]统治力数据, 耗时4毫秒
2016-08-08 05:13:04,019 INFO  [GroupServerScheduler_Worker-4] rydl.group.database.cache.CharacterCacheDataManager:saveCharacterDataDbImpl CharacterCacheDataManager.java:348 - 存储玩家[藍夢瑤(4506901631205376)]宠物抽卡数据, 耗时3毫秒
2016-08-08 05:13:04,022 INFO  [GroupServerScheduler_Worker-4] rydl.group.database.cache.CharacterCacheDataManager:saveCharacterDataDbImpl CharacterCacheDataManager.java:354 - 存储玩家[藍夢瑤(4506901631205376)]签到数据, 耗时3毫秒
2016-08-08 05:13:04,022 INFO  [GroupServerScheduler_Worker-4] rydl.group.database.cache.CharacterCacheDataManager:saveCharacterDataDbImpl CharacterCacheDataManager.java:356 - 存储玩家[藍夢瑤(4506901631205376)]数据到数据库结束，总共耗时34毫秒
2016-08-08 05:13:04,359 ERROR [server-log-thread-2] rydl.commons.log.LogSystem$LogSave:run LogSystem.java:52 - 
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: com.mysql.jdbc.exceptions.MySQLTimeoutException: Statement cancelled due to timeout or client request
### The error may involve rydl.commons.log.mybatis.dao.AccountLoginLogModelMapper.insert-Inline
### The error occurred while setting parameters
### SQL: insert into t_account_login (logType, localAccount,  platform, platformUserId,  deviceType, deviceOS,  deviceMac, onlineTime,  reason, logIP, logComment,  logTime, netType) values (?, ?,  ?, ?,  ?, ?,  ?, ?,  ?, ?, ?,  ?, ?)
### Cause: com.mysql.jdbc.exceptions.MySQLTimeoutException: Statement cancelled due to timeout or client request
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:172)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:157)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:52)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:53)
	at com.sun.proxy.$Proxy31.insert(Unknown Source)
	at rydl.commons.log.LogSystem$LogSave.run(LogSystem.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.MySQLTimeoutException: Statement cancelled due to timeout or client request
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2765)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:989)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:45)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:73)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:115)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:170)
	... 10 more
2016-08-08 05:13:06,247 INFO  [main-logic-thread-1] rydl.group.msg.handlers.LoginGroupHandler:handle LoginGroupHandler.java:493 - 开始接收玩家数据





小概率事件



2
2016-08-09 11:11:08,394 INFO  [world-logic-thread-1] rydl.zone.msg.handlers.DominantGroupHandler:handle DominantGroupHandler.java:47 - open dominant
2016-08-09 11:11:08,695 ERROR [world-logic-thread-1] rydl.zone.msg.handlers.MapGroupHandler:handle MapGroupHandler.java:838 - 
java.lang.NullPointerException
	at rydl.zone.model.maps.WorldPosition.getMapId(WorldPosition.java:55)
	at rydl.zone.model.gameobjects.VisibleObject.getMapID(VisibleObject.java:141)
	at rydl.zone.services.PlayerService.moveMapByMetaMapID(PlayerService.java:795)
	at rydl.zone.msg.handlers.MapGroupHandler.handle(MapGroupHandler.java:228)
	at rydl.zone.model.maps.World.handleMessage(World.java:322)
	at rydl.zone.model.maps.World.run(World.java:270)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-08-09 11:11:08,696 INFO  [world-logic-thread-1] rydl.zone.ai.AIStateIdleStrategyLookEnemy:startLookforEnemy AIStateIdleStrategyLookEnemy.java:97 - idle state confirm target id4522736

1
2016-08-09 17:59:59,890 INFO  [world-logic-thread-1] rydl.zone.msg.handlers.LoginGroupHandler:handle LoginGroupHandler.java:230 - 玩家[咲夜]进入场景
2016-08-09 18:00:00,046 ERROR [world-logic-thread-1] rydl.zone.msg.handlers.ArenaGroupHandler:handle ArenaGroupHandler.java:137 - 
java.lang.NullPointerException
	at rydl.zone.quest.QuestSystem.doingQuestIterator(QuestSystem.java:72)
	at rydl.zone.services.QuestService.onEvent(QuestService.java:386)
	at rydl.zone.services.PlayerService.changeResource(PlayerService.java:1095)
	at rydl.zone.msg.handlers.ArenaGroupHandler.handle(ArenaGroupHandler.java:127)
	at rydl.zone.model.maps.World.handleMessage(World.java:322)
	at rydl.zone.model.maps.World.run(World.java:270)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-08-09 18:00:00,241 INFO  [world-logic-thread-1] rydl.zone.services.PlayerService:moveMap PlayerService.java:828 - 玩家[七七(vstargame_s1_4876723)]要从地图[王者争霸(1102)]传送到地图[卡鲁格纳(2,1)]在同一游戏世界(World)中







无法排查
2016-08-04 00:18:16,955 ERROR [world-logic-thread-3] rydl.zone.msg.handlers.SkillGroupHandler:handle SkillGroupHandler.java:108 - 
java.lang.NullPointerException
2016-08-04 00:18:17,055 INFO  [world-logic-thread-1] rydl.zone.services.PlayerService:syncAddObjectToClient PlayerService.java:626 - 向玩家[俏淚]同步了玩家[暗夜星辰]的信息






已排查

并行流出现空数据造成的
2016-08-04 02:19:24,362 ERROR [world-logic-thread-3] rydl.zone.msg.handlers.MapGroupHandler:handle MapGroupHandler.java:846 - 
java.lang.NullPointerException
	at rydl.zone.model.maps.EquipMultiplayerMapInstance.enterNextWaveImpl(EquipMultiplayerMapInstance.java:280)
	at rydl.zone.model.maps.EquipMultiplayerMapInstance.onEnterNextWave(EquipMultiplayerMapInstance.java:260)
	at rydl.zone.msg.handlers.MapGroupHandler.handle(MapGroupHandler.java:88)
	at rydl.zone.model.maps.World.handleMessage(World.java:322)
	at rydl.zone.model.maps.World.run(World.java:270)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2016-08-04 06:59:47,796 ERROR [world-logic-thread-5] rydl.zone.msg.handlers.MapGroupHandler:handle MapGroupHandler.java:846 - 
java.lang.NullPointerException
	at rydl.zone.model.maps.ProtectDiamondMapInstance.onPlayerLeaveMap(ProtectDiamondMapInstance.java:487)
	at rydl.zone.model.maps.CopyMapInstance.leaveMap(CopyMapInstance.java:38)
	at rydl.zone.model.maps.CopyMap.leaveMap(CopyMap.java:84)
	at rydl.zone.msg.handlers.MapGroupHandler.handle(MapGroupHandler.java:390)
	at rydl.zone.model.maps.World.handleMessage(World.java:322)
	at rydl.zone.model.maps.World.run(World.java:270)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


2016-08-04 10:45:30,423 ERROR [world-logic-thread-5] rydl.zone.model.maps.MapManager:heartBeat MapManager.java:199 - 
java.lang.NullPointerException
	at rydl.zone.model.maps.ProtectDiamondMapInstance.onWaveEnd(ProtectDiamondMapInstance.java:224)
	at rydl.zone.model.maps.MapMonsterManager.onMonsterDie(MapMonsterManager.java:190)
	at rydl.zone.model.maps.GameMapInstance.onMonsterDie(GameMapInstance.java:548)
	at rydl.zone.model.maps.ProtectDiamondMapInstance.onMonsterDie(ProtectDiamondMapInstance.java:609)
	at rydl.zone.model.gameobjects.Monster.onDead(Monster.java:299)
	at rydl.zone.model.gameobjects.Creature.changeHp(Creature.java:441)
	at rydl.zone.skill.Skill.calculateDmg(Skill.java:518)
	at rydl.zone.skill.Skill.updateSkillPiloting(Skill.java:323)
	at rydl.zone.skill.Skill.heartBeat(Skill.java:288)
	at rydl.zone.skill.CombatEngine.heartBeat(CombatEngine.java:125)
	at rydl.zone.model.gameobjects.player.Player.heartBeat(Player.java:383)
	at rydl.zone.model.maps.GameMapInstance.heartBeat(GameMapInstance.java:175)
	at rydl.zone.model.maps.ProtectDiamondMapInstance.heartBeat(ProtectDiamondMapInstance.java:139)
	at rydl.zone.model.maps.CopyMap.heartBeat(CopyMap.java:148)
	at rydl.zone.model.maps.MapManager.heartBeat(MapManager.java:197)
	at rydl.zone.model.maps.World.run(World.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	
	
sql错误 已修改
2016-08-09 07:35:27,683 INFO  [main-logic-thread-1] rydl.group.faction.Faction:removeMember Faction.java:248 - 公会成员4506905352339456,从公会4506905352339456删除
2016-08-09 07:35:27,848 ERROR [GroupServerScheduler_Worker-2] rydl.group.database.dao.FactionDAO:deleteFaction FactionDAO.java:264 - Unknown column 'f_dismissTime' in 'field list'
2016-08-09 07:35:29,742 INFO  [main-logic-thread-1] rydl.group.services.UserService:userLogin UserService.java:138 - 用户[vstargame_s1_410531]强制登录组服务器，前用户在等待重连状态


添加排查日志
2016-08-05 23:04:13,919 ERROR [main-logic-thread-1] rydl.group.msg.handlers.FactionGroupHandler:handle FactionGroupHandler.java:707 - 公会争霸出现错误,code:740935:null


已修改
702
2016-08-08 15:39:52,956 INFO  [world-logic-thread-1] rydl.zone.services.PlayerService:savePlayerDataToDB PlayerService.java:287 - 开始存储玩家[無花果]数据
2016-08-08 15:39:52,957 INFO  [world-logic-thread-1] rydl.zone.services.PlayerService:savePlayerDataToDB PlayerService.java:376 - 存储玩家[無花果]数据结束
2016-08-08 15:39:52,988 ERROR [world-logic-thread-5] rydl.zone.msg.handlers.SkillGroupHandler:handle SkillGroupHandler.java:108 - 
org.apache.commons.math3.exception.MathArithmeticException: cannot normalize a zero norm vector
	at org.apache.commons.math3.geometry.euclidean.threed.Vector3D.normalize(Vector3D.java:299)
	at rydl.zone.skill.Skill.isTarget(Skill.java:906)
	at rydl.zone.skill.Skill.calcSkillTargetList(Skill.java:741)
	at rydl.zone.skill.Skill.castSkill(Skill.java:555)
	at rydl.zone.skill.CombatEngine.castSkill(CombatEngine.java:154)
	at rydl.zone.msg.handlers.SkillGroupHandler.handle(SkillGroupHandler.java:36)
	at rydl.zone.model.maps.World.handleMessage(World.java:322)
	at rydl.zone.model.maps.World.run(World.java:270)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-08-08 15:39:53,288 ERROR [world-logic-thread-5] rydl.zone.msg.handlers.SkillGroupHandler:handle SkillGroupHandler.java:108 - 
org.apache.commons.math3.exception.MathArithmeticException: cannot normalize a zero norm vector
	at org.apache.commons.math3.geometry.euclidean.threed.Vector3D.normalize(Vector3D.java:299)
	at rydl.zone.skill.Skill.isTarget(Skill.java:906)
	at rydl.zone.skill.Skill.calcSkillTargetList(Skill.java:741)
	at rydl.zone.skill.Skill.castSkill(Skill.java:555)
	at rydl.zone.skill.CombatEngine.castSkill(CombatEngine.java:154)
	at rydl.zone.msg.handlers.SkillGroupHandler.handle(SkillGroupHandler.java:36)
	at rydl.zone.model.maps.World.handleMessage(World.java:322)
	at rydl.zone.model.maps.World.run(World.java:270)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

添加排查日志
4541
2016-08-09 00:16:07,307 INFO  [world-logic-thread-1] rydl.zone.msg.handlers.LoginGroupHandler:handle LoginGroupHandler.java:230 - 玩家[提拉米蘇]进入场景
2016-08-09 00:16:07,376 ERROR [world-logic-thread-5] rydl.commons.cycle.CycleSystem:checkCycle CycleSystem.java:60 - 无数据的周期ID:0
2016-08-09 00:16:07,376 ERROR [world-logic-thread-5] rydl.commons.cycle.CycleSystem:checkCycle CycleSystem.java:60 - 无数据的周期ID:0
2016-08-09 00:16:07,457 INFO  [world-logic-thread-3] rydl.zone.ai.AIStateIdleStrategyLookEnemy:startLookforEnemy AIStateIdleStrategyLookEnemy.java:97 - idle state confirm target id4522971

	

登陆服务器的

2016-08-09 09:45:22,080 ERROR [pool-3-thread-10] rydl.login.platform.LoginService:checkLogin LoginService.java:341 - Vstargame登录验证异常. checkUrl: http://login.vstargame.com/login/gameCheckLogin. param: {clientid=1048, flag=b050ba74372c988855f19f08f52b1aeb, time=1470707121, userid=5151087, token=175180f03d6ecac31fdac95ede1e2e2d68ae5819}
修改日志记录方式，添加返回值


已修改
45
2016-08-07 02:02:30,068 INFO  [world-logic-thread-1] rydl.zone.msg.handlers.DominantGroupHandler:handle DominantGroupHandler.java:47 - open dominant
2016-08-07 02:02:30,068 ERROR [world-logic-thread-1] rydl.zone.msg.handlers.DominantGroupHandler:handle DominantGroupHandler.java:193 - 
java.lang.NullPointerException
	at rydl.zone.services.DominantServices.sweep(DominantServices.java:306)
	at rydl.zone.msg.handlers.DominantGroupHandler.handle(DominantGroupHandler.java:128)
	at rydl.zone.model.maps.World.handleMessage(World.java:322)
	at rydl.zone.model.maps.World.run(World.java:270)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)	


	
添加排查日志
2016-08-09 00:11:37,841 INFO  [world-logic-thread-1] rydl.zone.services.PlayerService:savePlayerDataToDB PlayerService.java:376 - 存储玩家[提拉米蘇]数据结束
2016-08-09 00:11:37,880 ERROR [nioEventLoopGroup-4-1] rydl.zone.model.maps.WorldManager:handleMessage WorldManager.java:183 - Push消息[7945]时未找到该ID[4522247]的World!!!
2016-08-09 00:11:37,939 INFO  [world-logic-thread-1] rydl.zone.services.PlayerService:moveMap PlayerService.java:828 - 玩家[伍德·尼爾森(vstargame_s1_5143175)]要从地图[竞技场(1001)]传送到地图[卡鲁格纳(2,1)]在同一游戏世界(World)中


修改日志系统，保存魂石ID
2016-08-09 16:09:04,093 INFO  [GroupServerScheduler_Worker-1] rydl.group.database.cache.CharacterCacheDataManager:saveCharacterDataDbImpl CharacterCacheDataManager.java:318 - 存储玩家[拉森·克莉絲(4506891931418624)]基础数据表, 耗时3毫秒
2016-08-09 16:09:04,120 INFO  [GroupServerScheduler_Worker-1] rydl.group.database.cache.CharacterCacheDataManager:saveCharacterDataDbImpl CharacterCacheDataManager.java:324 - 存储玩家[拉森·克莉絲(4506891931418624)]宠物数据表, 耗时27毫秒
2016-08-09 16:09:04,129 INFO  [GroupServerScheduler_Worker-1] rydl.group.database.cache.CharacterCacheDataManager:saveCharacterDataDbImpl CharacterCacheDataManager.java:330 - 存储玩家[拉森·克莉絲(4506891931418624)]物品数据表, 耗时9毫秒
2016-08-09 16:09:04,131 ERROR [GroupServerScheduler_Worker-1] rydl.group.database.cache.CharacterCacheDataManager:saveDbImpl CharacterCacheDataManager.java:299 - 
java.sql.BatchUpdateException: Duplicate entry '4524496159178752' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor99.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1160)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1773)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1257)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:959)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:1723)
	at rydl.group.database.dao.AstrologyStoneModelDAO$3.handleWrite(AstrologyStoneModelDAO.java:207)
	at rydl.commons.kxdb.KxDB.saveOrUpdate(KxDB.java:135)
	at rydl.group.database.dao.AstrologyStoneModelDAO.batchInsert(AstrologyStoneModelDAO.java:189)
	at rydl.group.database.services.AstrologyDbService.saveStones(AstrologyDbService.java:40)
	at rydl.group.database.cache.CharacterCacheDataManager.saveCharacterDataDbImpl(CharacterCacheDataManager.java:333)
	at rydl.group.database.cache.CharacterCacheDataManager.saveDbImpl(CharacterCacheDataManager.java:296)
	at rydl.group.database.job.CharacterSaveDbJob.execute(CharacterSaveDbJob.java:21)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '4524496159178752' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor26.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1751)

添加id
2016-08-05 23:01:36,765 ERROR [main-logic-thread-1] rydl.group.msg.handlers.FactionGroupHandler:handle FactionGroupHandler.java:959 - 
java.lang.NullPointerException
	at rydl.group.msg.handlers.FactionGroupHandler.handle(FactionGroupHandler.java:665)
	at rydl.group.GroupLogic.handleMessage(GroupLogic.java:197)
	at rydl.group.GroupLogic.run(GroupLogic.java:114)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	
	
添加日志
1
2016-08-09 11:02:26,339 INFO  [world-logic-thread-1] rydl.zone.msg.handlers.LoginGroupHandler:handle LoginGroupHandler.java:230 - 玩家[小楓]进入场景
2016-08-09 11:02:26,386 ERROR [world-logic-thread-1] rydl.zone.msg.handlers.LoginGroupHandler:handle LoginGroupHandler.java:302 - 
java.lang.NullPointerException
	at rydl.zone.model.gameobjects.VisibleObject.enterMap(VisibleObject.java:181)
	at rydl.zone.model.gameobjects.player.Player.enterMap(Player.java:635)
	at rydl.zone.model.maps.GameMapInstance.enterMap(GameMapInstance.java:371)
	at rydl.zone.model.maps.CommonMapInstance.enterMap(CommonMapInstance.java:52)
	at rydl.zone.model.maps.CommonMap.enterMap(CommonMap.java:65)
	at rydl.zone.msg.handlers.LoginGroupHandler.handle(LoginGroupHandler.java:229)
	at rydl.zone.model.maps.World.handleMessage(World.java:322)
	at rydl.zone.model.maps.World.run(World.java:270)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-08-09 11:02:26,582 INFO  [world-logic-thread-1] rydl.zone.msg.handlers.DominantGroupHandler:handle DominantGroupHandler.java:47 - open dominant

















	